services:
  sonarr:
    image: ghcr.io/podmania/sonarr:latest
    # set to host user id and gid
    # defaults to 1000:1000
    # user: 1001:1001
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:   
      - ./config:/config
      # Per Sonarr best practice, downloads and media should both be under /data to avoid remote folder mapping and performance bottlenecks
      # ex. /data/tv, /data/downloads
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro # optional: use either TZ variable or localtime mapping, not both
    # environment:
    #   - TZ=America/New_York
    restart: unless-stopped

