name: Build & Publish

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild current version'
        required: false
        default: false
        type: boolean

jobs:
  build:
    uses: podmania/actions/.github/workflows/build-publish.yml@main
    with:
      version-output: sonarrVersion
      images: '[{"name":"sonarr","package":"sonarr-image"}]'
      force_rebuild: ${{ github.event.inputs.force_rebuild == 'true' }}
