name: Update version
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    uses: podmania/.github/.github/workflows/update-version.yml@main
    with:
      package: sonarr
      upstream: Sonarr/Sonarr
      tag-prefix: v
      dep-type: dotnet
